# Generated by Django 5.2 on 2025-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botconfig",
            name="channel_id",
            field=models.CharField(
                blank=True,
                help_text="Discord channel ID for test messages",
                max_length=20,
            ),
        ),
    ]
