name: Social_Cube
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - django=4.2
  - pip=23.1
  - pip:
    - "discord.py==2.3.2"
    - "python-dotenv==1.0.0"
    - "django-crispy-forms==2.0"
    - "crispy-bootstrap5==0.7" 