name: social_cube
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - django=4.2
  - pip
  - pip:
    - django-crispy-forms
    - django-environ
    - whitenoise
    - gunicorn
    # Test dependencies
    - pytest
    - pytest-django
    - pytest-cov
    - pytest-xdist
    - factory-boy
    - faker 