# Generated by Django 5.2 on 2025-04-27 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("auth_success", "Authentication Success"),
                            ("auth_failure", "Authentication Failure"),
                            ("permission", "Permission Change"),
                            ("admin", "Admin Action"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("entity_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="logging_sys_timesta_be48ca_idx"
                    ),
                    models.Index(
                        fields=["user"], name="logging_sys_user_id_b23428_idx"
                    ),
                    models.Index(
                        fields=["action"], name="logging_sys_action_f43023_idx"
                    ),
                    models.Index(
                        fields=["entity_type"], name="logging_sys_entity__d2cdd2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="ERROR",
                        max_length=10,
                    ),
                ),
                ("logger_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("exception_type", models.CharField(blank=True, max_length=255)),
                ("traceback", models.TextField(blank=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="logging_sys_timesta_7448d7_idx"
                    ),
                    models.Index(fields=["level"], name="logging_sys_level_2cccbd_idx"),
                    models.Index(
                        fields=["logger_name"], name="logging_sys_logger__ad4d04_idx"
                    ),
                    models.Index(
                        fields=["exception_type"], name="logging_sys_excepti_d633b1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.IntegerField()),
                (
                    "duration",
                    models.FloatField(help_text="Request duration in seconds"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_size", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="logging_sys_timesta_4b4de6_idx"
                    ),
                    models.Index(fields=["path"], name="logging_sys_path_8df5f8_idx"),
                    models.Index(
                        fields=["status_code"], name="logging_sys_status__6d8b36_idx"
                    ),
                    models.Index(
                        fields=["user"], name="logging_sys_user_id_e35ac6_idx"
                    ),
                ],
            },
        ),
    ]
