# Generated by Django 5.2 on 2025-04-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("token", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="bot_avatars/"),
                ),
                ("prefix", models.CharField(default="!", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("moderation", "Moderation"),
                            ("utility", "Utility"),
                            ("fun", "Fun"),
                            ("music", "Music"),
                            ("other", "Other"),
                        ],
                        default="utility",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("syntax", models.CharField(blank=True, max_length=255)),
                ("options", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="dashboard.bot",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "bot")},
            },
        ),
        migrations.CreateModel(
            name="CommandExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20)),
                ("user_name", models.CharField(max_length=100)),
                ("server_id", models.CharField(max_length=20)),
                ("server_name", models.CharField(max_length=100)),
                ("channel_id", models.CharField(max_length=20)),
                ("parameters", models.TextField(blank=True)),
                ("is_success", models.BooleanField(default=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.command",
                    ),
                ),
            ],
        ),
    ]
