# Generated by Django 5.2 on 2025-04-27 10:18

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_tasktag_task_tasktagassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_dark_mode", models.BooleanField(default=False)),
                (
                    "dashboard_layout",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("compact", "Compact"),
                            ("expanded", "Expanded"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("discord_notifications", models.BooleanField(default=True)),
                ("notify_on_bot_status_change", models.BooleanField(default=True)),
                ("notify_on_server_join", models.BooleanField(default=True)),
                ("notify_on_command_usage", models.BooleanField(default=False)),
                ("notify_on_error", models.BooleanField(default=True)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
