# Generated by Django 5.2 on 2025-04-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
