# Generated by Django 5.2 on 2025-04-26 16:00

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("owner_id", models.CharField(max_length=100, null=True)),
                ("member_count", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync", models.DateTimeField(auto_now=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guilds",
                        to="bot_management.bot",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("bot", "guild_id")},
            },
        ),
        migrations.CreateModel(
            name="GuildSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(default="!", max_length=10)),
                (
                    "notification_channel_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("welcome_message", models.TextField(blank=True, null=True)),
                ("goodbye_message", models.TextField(blank=True, null=True)),
                ("enable_welcome_messages", models.BooleanField(default=False)),
                ("enable_goodbye_messages", models.BooleanField(default=False)),
                ("enable_member_tracking", models.BooleanField(default=False)),
                ("enable_moderation", models.BooleanField(default=False)),
                (
                    "admin_role_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "moderator_role_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "custom_settings",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="bot_management.guild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuildChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Text"),
                            (1, "DM"),
                            (2, "Voice"),
                            (3, "Group DM"),
                            (4, "Category"),
                            (5, "Announcement"),
                            (10, "Announcement Thread"),
                            (11, "Public Thread"),
                            (12, "Private Thread"),
                            (13, "Stage Voice"),
                            (14, "Directory"),
                            (15, "Forum"),
                        ],
                        default=0,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_nsfw", models.BooleanField(default=False)),
                ("topic", models.CharField(blank=True, max_length=1024, null=True)),
                ("last_sync", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="bot_management.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
                "unique_together": {("guild", "channel_id")},
            },
        ),
    ]
