# Generated by Django 5.2 on 2025-04-26 16:53

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0002_guild_guildsettings_guildchannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "CHAT_INPUT"), (2, "USER"), (3, "MESSAGE")],
                        default=1,
                    ),
                ),
                (
                    "default_member_permissions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_dm_enabled", models.BooleanField(default=True)),
                ("is_nsfw", models.BooleanField(default=False)),
                ("command_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "command_data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="bot_management.bot",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="bot_management.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("bot", "guild", "name")},
            },
        ),
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="bot_management.command",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommandOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=100)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "SUB_COMMAND"),
                            (2, "SUB_COMMAND_GROUP"),
                            (3, "STRING"),
                            (4, "INTEGER"),
                            (5, "BOOLEAN"),
                            (6, "USER"),
                            (7, "CHANNEL"),
                            (8, "ROLE"),
                            (9, "MENTIONABLE"),
                            (10, "NUMBER"),
                            (11, "ATTACHMENT"),
                        ]
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "option_data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="bot_management.command",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="bot_management.commandoption",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
